[build-system]
requires = [
  "build",
  "wheel",
  "setuptools>=45",
  "scikit-build-core>=0.3.3",
  "pybind11",
  "cmake",
  "ninja",
  "rcs-core>=0.7.2",
]
build-backend = "scikit_build_core.build"

[project]
name = "rcs_panda"
version = "0.7.2"
description = "RCS libfranka integration"
dependencies = ["rcs-core>=0.7.2"]
readme = "README.md"
license = { text = "AGPL-3.0-or-later" }
maintainers = [{ name = "Tobias Jülg", email = "tobias.juelg@utn.de" }]
authors = [{ name = "Tobias Jülg", email = "tobias.juelg@utn.de" }]
requires-python = ">=3.11"


[tool.scikit-build]
build.verbose = true
build.targets = ["_core"]
logging.level = "INFO"
build-dir = "build"
wheel.packages = ["src/rcs_panda"]
install.components = ["python_package"]

[tool.cibuildwheel]
skip = ["cp314*", "*-musllinux*"]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel} --exclude librcs.so --exclude libpinocchio_default.so.3.7.0 --exclude libpinocchio_parsers.so.3.7.0"

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
profile = "black"
