stages:
  - build_cpp
  - lint_cpp
  - build_py
  - lint_py

build_cpp:
  stage: build_cpp
  script:
    - clang-format --dry-run -Werror -i $(find src -name '*.cpp' -o -name '*.cc' -o -name '*.h')
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -B build -G Ninja -S .
    - cmake --build build
    - clang-tidy -p=build --warnings-as-errors='*' $(find src -name '*.cpp' -o -name '*.cc' -name '*.h')

build_py:
  stage: build_py
  script: echo TODO

lint_py:
  stage: lint_py
  script: echo TODO
