stages:
  - cpp
  - python_pre_install
  - python
  - python_post_install

cpp_format:
  stage: cpp
  script:
    - make cppcheckformat

gcc_compile:
  stage: cpp
  script:
    - make gcccompile

clang_compile:
  stage: cpp
  script:
    - make clangcompile
    - make cpplint

python_dependencies:
  stage: python_pre_install
  script:
    - pip3 install --break-system-packages -r requirements_dev.txt

python_format:
  stage: python
  script:
    - make pycheckformat 

python_lint:
  stage: python
  script:
    - make pylint 

python_build:
  stage: python
  script:
    - python3 -m build --wheel --outdir dist/
    - pip3 install --break-system-packages dist/*.whl
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
    paths:
      - "dist/*.whl"

python_stubgencheck:
  stage: python_post_install
  script:
    - make stubgen && git diff --exit-code

python_unittest:
  stage: python_post_install
  script:
    - make pytest
