version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: rcs-dev
    container_name: rcs-dev
    tty: true
    stdin_open: true
    volumes:
      - .:/home/devuser/project
    environment:
      - DISPLAY=${DISPLAY}
    shm_size: "2g"

  gui:
    user : root
    image: rcs-dev
    container_name: gui-dev
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      #- .:/home/devuser/project
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    shm_size: "2g"
    privileged: true
    network_mode: host
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock:
        soft: 8428281856
        hard: 8428281856
  gpu:
    user : root
    image: rcs-dev
    container_name: gpu-dev
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      #- .:/home/devuser/project
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    shm_size: "2g"
    runtime: nvidia
    privileged: true
    network_mode: host
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock:
        soft: 8428281856
        hard: 8428281856
