[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rcs_sb3"
version = "0.7.1"
description = "Stable-Baselines3 integration for RCS environments"
dependencies = ["rcs>=0.7.1", "stable-baselines3>=2.3.0"]
readme = "README.md"
maintainers = [{ name = "Seongjin Bien", email = "seongjin.bien@utn.de" }]
authors = [{ name = "Seongjin Bien", email = "seongjin.bien@utn.de" }]
requires-python = ">=3.11"

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
profile = "black"
