version: "3.8"

services:
  run:
    # Old-compose compatible GPU enablement
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "all"

