name: k4a python lib build
on:
  workflow_call:
  pull_request:
    paths:
    - "install_kinect_k4a.sh"

jobs:
  k4a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Create python wheel
        run: ./install_kinect_k4a.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: k4a
          path: dist/*.whl
          retention-days: 90
