name: Python
on:
  workflow_call:
  pull_request:
    paths:
      - "python/**"
      - "src/pybind/**"
      - ".github/workflows/**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install linting and formatting dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: Check formatting
        run: make pycheckformat

  pythonpackage:
    runs-on: ubuntu-latest
    env:
      CC: clang-15
      CXX: clang++-15
    steps:
      - uses: actions/checkout@v4
      - name: Install CPP dependencies
        run: xargs sudo apt-get -y install < debian_deps.txt
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install building dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: Create python wheel
        run: python -m build --no-isolation --wheel --outdir dist/
      - name: Install the wheel package
        run: python -m pip install dist/*.whl
      - name: Code linting
        run: make pylint
      - name: Check that stub files are up-to-date
        run: make stubgen && git diff --exit-code
      - name: Ensure all unittests(pytest) are passing
        run: make pytest
