name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  pythonpackage:
    runs-on: ubuntu-latest
    env:
      CC: clang-15
      CXX: clang++-15
    steps:
      - uses: actions/checkout@v4
      - name: Install CPP dependencies
        run: sudo apt-get install --yes build-essential cmake git libpoco-dev libeigen3-dev libxslt-dev libcoin-dev libccd-dev libglfw3-dev libboost-all-dev liblzma-dev ninja-build clang-15
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install building dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: Create python wheel
        run: python -m build --wheel --outdir dist/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rcsss
          path: dist/*.whl
          retention-days: 30
      # create github release
      # upload the wheel to the release and pyPI