name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install CPP dependencies
        run: xargs sudo apt -y install < debian_deps.txt
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install building dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: Create python wheel
        run: python -m build --wheel --outdir dist/
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          changelog_increment_filename: body.md
          commit: false
          push: false
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.REVISION }}
          bodyFile: "body.md"
          artifacts: "dist/*.whl"
          skipIfReleaseExists: true
      # TODO: upload the wheel to the release and pyPI